### ISSUE TITLE
Cant send keyboard inputs?

### ISSUE THREAD

**Issue by Xag8031** [ferdinandschober/lan-mouse#6]
I am currently trying to use this to use 2 rigs with one keyboard and mouse on hyprland (wlroots based) but only my mouse seems to be sending properly. Any help as my configs are probably the problem? Files are attached, hopefully should be txt  as github hates me and won't allow toml's
[config.toml client](https://github.com/ferdinandschober/lan-mouse/files/11154234/config.toml.txt)
[config.toml server](https://github.com/ferdinandschober/lan-mouse/files/11154240/config.toml.txt)

**Comment by ferdinandschober** [comment]
If your mouse is working, the config is correct. I would assume that Hyprland currently does not support the virtual-keyboard protocol. I can give you more info once I test this myself.

**Comment by ferdinandschober** [comment]
@Xag8031 can you give some more information? I just tested this and it works for me (writing this from my laptop on my Desktop using Hyprland on both).
Does the log say anything?

**Comment by Xag8031** [comment]
Sorry to get back to you so late. I don't see any log files and it doesn't show any errors.

**Comment by ferdinandschober** [comment]
When you run it, it should print  "Connecting to {client} done!".
Can you verify this is the case on both devices and shows the correct ip adresses?

Make sure you allow the respective ports for _both_ udp and tcp connections in your firewall in case you are using one.

Also please try using the same port on both devices to rule that out.

The version of Hyprland and exact commit of lan-mouse you are using would be useful as well, so I can try to reproduce this.

**Comment by Xag8031** [comment]
Okay, I think I got it to work thank you.

**Comment by ferdinandschober** [comment]
Do you know what the issue was or what exactly fixed the problem?

**Comment by Xag8031** [comment]
I think it was slow data transfer. I got a better Ethernet cable to hook them together and it worked.

**Comment by ferdinandschober** [comment]
That sounds like something I should investigate. Thank you for your feedback!
